package ruiz.ssh.model;
// Generated 2017-11-30 15:42:34 by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * ShipBasic generated by hbm2java
 */
public class ShipBasic implements java.io.Serializable {

	private int idship;
	private String shipName;
	private String flagNation;
	private String shipPort;
	private String shipType;
	private Date bulitTime;
	private Integer age;
	private String seaZone;
	private Integer motorAm;
	private BigDecimal singleHp;
	private BigDecimal totalHp;
	private BigDecimal powerKw;
	private BigDecimal length;
	private BigDecimal width;
	private BigDecimal depth;
	private String iceLevel;
	private String fireExtinguishAm;
	private String callNum;
	private BigDecimal draftDepth;
	private BigDecimal weight;
	private BigDecimal netWeight;
	private BigDecimal loadWeight;
	private BigDecimal deckLen;
	private BigDecimal deckWidth;
	private BigDecimal deckArea;
	private Integer bowThrusterAm;
	private BigDecimal bowThrusterPower;
	private BigDecimal sternThrusterHp;
	private Byte isAnchor;
	private BigDecimal maxSpeed;
	private BigDecimal ecoSpeed;
	private Integer maintowAmount;
	private BigDecimal maintowLen;
	private BigDecimal maitowDiameter;
	private BigDecimal pullForce;
	private BigDecimal drinkingwater;
	private BigDecimal boreholewater;
	private Integer oilbunker;
	private Integer bulkcan;
	private Integer mudtank;
	private Integer brinetank;
	private BigDecimal deckLoad;
	private BigDecimal deckStrength;
	private Integer passengerCapacity;
	private Byte ableoilfence;
	private String mainNavigationzone;
	private String mmsi;
	private Integer feDisplacement;
	private BigDecimal feRange;
	private BigDecimal feHeight;
	private BigDecimal foamTankCapacity;
	private Integer lifeboatAm;
	private BigDecimal lifeboatSp;
	private Integer lifeboatLoad;
	private Integer rescueboatAm;
	private Integer recueboatLoad;
	private Integer lifenresboatAm;
	private Integer lifenresboatLoad;
	private Integer raftAm;
	private Integer raftLoad;
	private BigDecimal treatmenttank;
	private BigDecimal oilrecoverytank;
	private Integer oilSprayingArmAm;
	private BigDecimal oilSprayingArmLen;
	private String communication;
	private Integer imoNum;
	private String factory;
	private String shipowner;
	private String company;

	public ShipBasic() {
	}

	public ShipBasic(int idship, String shipName) {
		this.idship = idship;
		this.shipName = shipName;
	}

	public ShipBasic(int idship, String shipName, String flagNation, String shipPort, String shipType, Date bulitTime,
			Integer age, String seaZone, Integer motorAm, BigDecimal singleHp, BigDecimal totalHp, BigDecimal powerKw,
			BigDecimal length, BigDecimal width, BigDecimal depth, String iceLevel, String fireExtinguishAm,
			String callNum, BigDecimal draftDepth, BigDecimal weight, BigDecimal netWeight, BigDecimal loadWeight,
			BigDecimal deckLen, BigDecimal deckWidth, BigDecimal deckArea, Integer bowThrusterAm,
			BigDecimal bowThrusterPower, BigDecimal sternThrusterHp, Byte isAnchor, BigDecimal maxSpeed,
			BigDecimal ecoSpeed, Integer maintowAmount, BigDecimal maintowLen, BigDecimal maitowDiameter,
			BigDecimal pullForce, BigDecimal drinkingwater, BigDecimal boreholewater, Integer oilbunker,
			Integer bulkcan, Integer mudtank, Integer brinetank, BigDecimal deckLoad, BigDecimal deckStrength,
			Integer passengerCapacity, Byte ableoilfence, String mainNavigationzone, String mmsi,
			Integer feDisplacement, BigDecimal feRange, BigDecimal feHeight, BigDecimal foamTankCapacity,
			Integer lifeboatAm, BigDecimal lifeboatSp, Integer lifeboatLoad, Integer rescueboatAm,
			Integer recueboatLoad, Integer lifenresboatAm, Integer lifenresboatLoad, Integer raftAm, Integer raftLoad,
			BigDecimal treatmenttank, BigDecimal oilrecoverytank, Integer oilSprayingArmAm,
			BigDecimal oilSprayingArmLen, String communication, Integer imoNum, String factory, String shipowner,
			String company) {
		this.idship = idship;
		this.shipName = shipName;
		this.flagNation = flagNation;
		this.shipPort = shipPort;
		this.shipType = shipType;
		this.bulitTime = bulitTime;
		this.age = age;
		this.seaZone = seaZone;
		this.motorAm = motorAm;
		this.singleHp = singleHp;
		this.totalHp = totalHp;
		this.powerKw = powerKw;
		this.length = length;
		this.width = width;
		this.depth = depth;
		this.iceLevel = iceLevel;
		this.fireExtinguishAm = fireExtinguishAm;
		this.callNum = callNum;
		this.draftDepth = draftDepth;
		this.weight = weight;
		this.netWeight = netWeight;
		this.loadWeight = loadWeight;
		this.deckLen = deckLen;
		this.deckWidth = deckWidth;
		this.deckArea = deckArea;
		this.bowThrusterAm = bowThrusterAm;
		this.bowThrusterPower = bowThrusterPower;
		this.sternThrusterHp = sternThrusterHp;
		this.isAnchor = isAnchor;
		this.maxSpeed = maxSpeed;
		this.ecoSpeed = ecoSpeed;
		this.maintowAmount = maintowAmount;
		this.maintowLen = maintowLen;
		this.maitowDiameter = maitowDiameter;
		this.pullForce = pullForce;
		this.drinkingwater = drinkingwater;
		this.boreholewater = boreholewater;
		this.oilbunker = oilbunker;
		this.bulkcan = bulkcan;
		this.mudtank = mudtank;
		this.brinetank = brinetank;
		this.deckLoad = deckLoad;
		this.deckStrength = deckStrength;
		this.passengerCapacity = passengerCapacity;
		this.ableoilfence = ableoilfence;
		this.mainNavigationzone = mainNavigationzone;
		this.mmsi = mmsi;
		this.feDisplacement = feDisplacement;
		this.feRange = feRange;
		this.feHeight = feHeight;
		this.foamTankCapacity = foamTankCapacity;
		this.lifeboatAm = lifeboatAm;
		this.lifeboatSp = lifeboatSp;
		this.lifeboatLoad = lifeboatLoad;
		this.rescueboatAm = rescueboatAm;
		this.recueboatLoad = recueboatLoad;
		this.lifenresboatAm = lifenresboatAm;
		this.lifenresboatLoad = lifenresboatLoad;
		this.raftAm = raftAm;
		this.raftLoad = raftLoad;
		this.treatmenttank = treatmenttank;
		this.oilrecoverytank = oilrecoverytank;
		this.oilSprayingArmAm = oilSprayingArmAm;
		this.oilSprayingArmLen = oilSprayingArmLen;
		this.communication = communication;
		this.imoNum = imoNum;
		this.factory = factory;
		this.shipowner = shipowner;
		this.company = company;
	}

	public int getIdship() {
		return this.idship;
	}

	public void setIdship(int idship) {
		this.idship = idship;
	}

	public String getShipName() {
		return this.shipName;
	}

	public void setShipName(String shipName) {
		this.shipName = shipName;
	}

	public String getFlagNation() {
		return this.flagNation;
	}

	public void setFlagNation(String flagNation) {
		this.flagNation = flagNation;
	}

	public String getShipPort() {
		return this.shipPort;
	}

	public void setShipPort(String shipPort) {
		this.shipPort = shipPort;
	}

	public String getShipType() {
		return this.shipType;
	}

	public void setShipType(String shipType) {
		this.shipType = shipType;
	}

	public Date getBulitTime() {
		return this.bulitTime;
	}

	public void setBulitTime(Date bulitTime) {
		this.bulitTime = bulitTime;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSeaZone() {
		return this.seaZone;
	}

	public void setSeaZone(String seaZone) {
		this.seaZone = seaZone;
	}

	public Integer getMotorAm() {
		return this.motorAm;
	}

	public void setMotorAm(Integer motorAm) {
		this.motorAm = motorAm;
	}

	public BigDecimal getSingleHp() {
		return this.singleHp;
	}

	public void setSingleHp(BigDecimal singleHp) {
		this.singleHp = singleHp;
	}

	public BigDecimal getTotalHp() {
		return this.totalHp;
	}

	public void setTotalHp(BigDecimal totalHp) {
		this.totalHp = totalHp;
	}

	public BigDecimal getPowerKw() {
		return this.powerKw;
	}

	public void setPowerKw(BigDecimal powerKw) {
		this.powerKw = powerKw;
	}

	public BigDecimal getLength() {
		return this.length;
	}

	public void setLength(BigDecimal length) {
		this.length = length;
	}

	public BigDecimal getWidth() {
		return this.width;
	}

	public void setWidth(BigDecimal width) {
		this.width = width;
	}

	public BigDecimal getDepth() {
		return this.depth;
	}

	public void setDepth(BigDecimal depth) {
		this.depth = depth;
	}

	public String getIceLevel() {
		return this.iceLevel;
	}

	public void setIceLevel(String iceLevel) {
		this.iceLevel = iceLevel;
	}

	public String getFireExtinguishAm() {
		return this.fireExtinguishAm;
	}

	public void setFireExtinguishAm(String fireExtinguishAm) {
		this.fireExtinguishAm = fireExtinguishAm;
	}

	public String getCallNum() {
		return this.callNum;
	}

	public void setCallNum(String callNum) {
		this.callNum = callNum;
	}

	public BigDecimal getDraftDepth() {
		return this.draftDepth;
	}

	public void setDraftDepth(BigDecimal draftDepth) {
		this.draftDepth = draftDepth;
	}

	public BigDecimal getWeight() {
		return this.weight;
	}

	public void setWeight(BigDecimal weight) {
		this.weight = weight;
	}

	public BigDecimal getNetWeight() {
		return this.netWeight;
	}

	public void setNetWeight(BigDecimal netWeight) {
		this.netWeight = netWeight;
	}

	public BigDecimal getLoadWeight() {
		return this.loadWeight;
	}

	public void setLoadWeight(BigDecimal loadWeight) {
		this.loadWeight = loadWeight;
	}

	public BigDecimal getDeckLen() {
		return this.deckLen;
	}

	public void setDeckLen(BigDecimal deckLen) {
		this.deckLen = deckLen;
	}

	public BigDecimal getDeckWidth() {
		return this.deckWidth;
	}

	public void setDeckWidth(BigDecimal deckWidth) {
		this.deckWidth = deckWidth;
	}

	public BigDecimal getDeckArea() {
		return this.deckArea;
	}

	public void setDeckArea(BigDecimal deckArea) {
		this.deckArea = deckArea;
	}

	public Integer getBowThrusterAm() {
		return this.bowThrusterAm;
	}

	public void setBowThrusterAm(Integer bowThrusterAm) {
		this.bowThrusterAm = bowThrusterAm;
	}

	public BigDecimal getBowThrusterPower() {
		return this.bowThrusterPower;
	}

	public void setBowThrusterPower(BigDecimal bowThrusterPower) {
		this.bowThrusterPower = bowThrusterPower;
	}

	public BigDecimal getSternThrusterHp() {
		return this.sternThrusterHp;
	}

	public void setSternThrusterHp(BigDecimal sternThrusterHp) {
		this.sternThrusterHp = sternThrusterHp;
	}

	public Byte getIsAnchor() {
		return this.isAnchor;
	}

	public void setIsAnchor(Byte isAnchor) {
		this.isAnchor = isAnchor;
	}

	public BigDecimal getMaxSpeed() {
		return this.maxSpeed;
	}

	public void setMaxSpeed(BigDecimal maxSpeed) {
		this.maxSpeed = maxSpeed;
	}

	public BigDecimal getEcoSpeed() {
		return this.ecoSpeed;
	}

	public void setEcoSpeed(BigDecimal ecoSpeed) {
		this.ecoSpeed = ecoSpeed;
	}

	public Integer getMaintowAmount() {
		return this.maintowAmount;
	}

	public void setMaintowAmount(Integer maintowAmount) {
		this.maintowAmount = maintowAmount;
	}

	public BigDecimal getMaintowLen() {
		return this.maintowLen;
	}

	public void setMaintowLen(BigDecimal maintowLen) {
		this.maintowLen = maintowLen;
	}

	public BigDecimal getMaitowDiameter() {
		return this.maitowDiameter;
	}

	public void setMaitowDiameter(BigDecimal maitowDiameter) {
		this.maitowDiameter = maitowDiameter;
	}

	public BigDecimal getPullForce() {
		return this.pullForce;
	}

	public void setPullForce(BigDecimal pullForce) {
		this.pullForce = pullForce;
	}

	public BigDecimal getDrinkingwater() {
		return this.drinkingwater;
	}

	public void setDrinkingwater(BigDecimal drinkingwater) {
		this.drinkingwater = drinkingwater;
	}

	public BigDecimal getBoreholewater() {
		return this.boreholewater;
	}

	public void setBoreholewater(BigDecimal boreholewater) {
		this.boreholewater = boreholewater;
	}

	public Integer getOilbunker() {
		return this.oilbunker;
	}

	public void setOilbunker(Integer oilbunker) {
		this.oilbunker = oilbunker;
	}

	public Integer getBulkcan() {
		return this.bulkcan;
	}

	public void setBulkcan(Integer bulkcan) {
		this.bulkcan = bulkcan;
	}

	public Integer getMudtank() {
		return this.mudtank;
	}

	public void setMudtank(Integer mudtank) {
		this.mudtank = mudtank;
	}

	public Integer getBrinetank() {
		return this.brinetank;
	}

	public void setBrinetank(Integer brinetank) {
		this.brinetank = brinetank;
	}

	public BigDecimal getDeckLoad() {
		return this.deckLoad;
	}

	public void setDeckLoad(BigDecimal deckLoad) {
		this.deckLoad = deckLoad;
	}

	public BigDecimal getDeckStrength() {
		return this.deckStrength;
	}

	public void setDeckStrength(BigDecimal deckStrength) {
		this.deckStrength = deckStrength;
	}

	public Integer getPassengerCapacity() {
		return this.passengerCapacity;
	}

	public void setPassengerCapacity(Integer passengerCapacity) {
		this.passengerCapacity = passengerCapacity;
	}

	public Byte getAbleoilfence() {
		return this.ableoilfence;
	}

	public void setAbleoilfence(Byte ableoilfence) {
		this.ableoilfence = ableoilfence;
	}

	public String getMainNavigationzone() {
		return this.mainNavigationzone;
	}

	public void setMainNavigationzone(String mainNavigationzone) {
		this.mainNavigationzone = mainNavigationzone;
	}

	public String getMmsi() {
		return this.mmsi;
	}

	public void setMmsi(String mmsi) {
		this.mmsi = mmsi;
	}

	public Integer getFeDisplacement() {
		return this.feDisplacement;
	}

	public void setFeDisplacement(Integer feDisplacement) {
		this.feDisplacement = feDisplacement;
	}

	public BigDecimal getFeRange() {
		return this.feRange;
	}

	public void setFeRange(BigDecimal feRange) {
		this.feRange = feRange;
	}

	public BigDecimal getFeHeight() {
		return this.feHeight;
	}

	public void setFeHeight(BigDecimal feHeight) {
		this.feHeight = feHeight;
	}

	public BigDecimal getFoamTankCapacity() {
		return this.foamTankCapacity;
	}

	public void setFoamTankCapacity(BigDecimal foamTankCapacity) {
		this.foamTankCapacity = foamTankCapacity;
	}

	public Integer getLifeboatAm() {
		return this.lifeboatAm;
	}

	public void setLifeboatAm(Integer lifeboatAm) {
		this.lifeboatAm = lifeboatAm;
	}

	public BigDecimal getLifeboatSp() {
		return this.lifeboatSp;
	}

	public void setLifeboatSp(BigDecimal lifeboatSp) {
		this.lifeboatSp = lifeboatSp;
	}

	public Integer getLifeboatLoad() {
		return this.lifeboatLoad;
	}

	public void setLifeboatLoad(Integer lifeboatLoad) {
		this.lifeboatLoad = lifeboatLoad;
	}

	public Integer getRescueboatAm() {
		return this.rescueboatAm;
	}

	public void setRescueboatAm(Integer rescueboatAm) {
		this.rescueboatAm = rescueboatAm;
	}

	public Integer getRecueboatLoad() {
		return this.recueboatLoad;
	}

	public void setRecueboatLoad(Integer recueboatLoad) {
		this.recueboatLoad = recueboatLoad;
	}

	public Integer getLifenresboatAm() {
		return this.lifenresboatAm;
	}

	public void setLifenresboatAm(Integer lifenresboatAm) {
		this.lifenresboatAm = lifenresboatAm;
	}

	public Integer getLifenresboatLoad() {
		return this.lifenresboatLoad;
	}

	public void setLifenresboatLoad(Integer lifenresboatLoad) {
		this.lifenresboatLoad = lifenresboatLoad;
	}

	public Integer getRaftAm() {
		return this.raftAm;
	}

	public void setRaftAm(Integer raftAm) {
		this.raftAm = raftAm;
	}

	public Integer getRaftLoad() {
		return this.raftLoad;
	}

	public void setRaftLoad(Integer raftLoad) {
		this.raftLoad = raftLoad;
	}

	public BigDecimal getTreatmenttank() {
		return this.treatmenttank;
	}

	public void setTreatmenttank(BigDecimal treatmenttank) {
		this.treatmenttank = treatmenttank;
	}

	public BigDecimal getOilrecoverytank() {
		return this.oilrecoverytank;
	}

	public void setOilrecoverytank(BigDecimal oilrecoverytank) {
		this.oilrecoverytank = oilrecoverytank;
	}

	public Integer getOilSprayingArmAm() {
		return this.oilSprayingArmAm;
	}

	public void setOilSprayingArmAm(Integer oilSprayingArmAm) {
		this.oilSprayingArmAm = oilSprayingArmAm;
	}

	public BigDecimal getOilSprayingArmLen() {
		return this.oilSprayingArmLen;
	}

	public void setOilSprayingArmLen(BigDecimal oilSprayingArmLen) {
		this.oilSprayingArmLen = oilSprayingArmLen;
	}

	public String getCommunication() {
		return this.communication;
	}

	public void setCommunication(String communication) {
		this.communication = communication;
	}

	public Integer getImoNum() {
		return this.imoNum;
	}

	public void setImoNum(Integer imoNum) {
		this.imoNum = imoNum;
	}

	public String getFactory() {
		return this.factory;
	}

	public void setFactory(String factory) {
		this.factory = factory;
	}

	public String getShipowner() {
		return this.shipowner;
	}

	public void setShipowner(String shipowner) {
		this.shipowner = shipowner;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

}
